### ISSUE TITLE
Does not work with default value for parameters

### ISSUE THREAD

**Issue by AdoPi** [fuckusername/jsencrypter#2]
Hi, 
Thanks for your encrypter!

I have an issue with it when I set a default value like 
`function(a,b = 1) {
}`

Encrypted file throws "variable is not defined" error

**Comment by togayther** [comment]
sorry, my english is soso. i think you should compile your js code from es6 , and then call this plugin.

**Comment by AdoPi** [comment]
Thanks for your reply; it works now :)
